let vm = new Vue({
  el:"#app",
  data:{
    petCustomFoodSelect:"乾糧",
    petCustomFoodType:["乾糧","主食","配菜"],
    petCustomFoodChosen:[],
    petCustomFoodMenu:[
      {
        type:"乾糧",
        name:"基本款餅乾",
        eng:"mainfood",
        price:100,
        cal:"30cal",
        imgURL:"../img/restaurant/mainFood.svg"
      },
      {
        type:"乾糧",
        name:"小魚造型餅乾",
        eng:"mainfood2",
        price:210,
        cal:"36cal",
        imgURL:"../img/restaurant/mainFood2.svg"
      },
      {
        type:"乾糧",
        name:"骨頭造型餅乾",
        eng:"mainfood3",
        price:210,
        cal:"40cal",
        imgURL:"../img/restaurant/mainFood3.svg"
      },
      {
        type:"乾糧",
        name:"圈圈造型餅乾",
        eng:"mainfood4",
        price:160,
        cal:"42cal",
        imgURL:"../img/restaurant/mainFood4.svg"
      },
      {
        type:"主食",
        name:"牛肉",
        eng:"meat",
        price:300,
        cal:"210cal",
        imgURL:"../img/restaurant/meat.svg"
      },
      {
        type:"主食",
        name:"魚肉",
        eng:"meat2",
        price:280,
        cal:"185cal",
        imgURL:"../img/restaurant/meat2.svg"
      },
      {
        type:"主食",
        name:"大明蝦",
        eng:"meat3",
        price:290,
        cal:"190cal",
        imgURL:"../img/restaurant/meat3.svg"
      },
      {
        type:"主食",
        name:"大雞腿",
        eng:"meat4",
        price:200,
        cal:"160cal",
        imgURL:"../img/restaurant/meat4.svg"
      },
      {
        type:"配菜",
        name:"紅蘿蔔",
        eng:"sidefood1",
        price:20,
        cal:"36cal",
        imgURL:"../img/restaurant/carrot.png"
      },
      {
        type:"配菜",
        name:"青菜",
        eng:"sidefood2",
        price:20,
        cal:"31cal",
        imgURL:"../img/restaurant/veg1.png"
      },
      {
        type:"配菜",
        name:"放山雞的蛋",
        eng:"sidefood3",
        price:20,
        cal:"33cal",
        imgURL:"../img/restaurant/sliceEgg.svg"
      },
      {
        type:"配菜",
        name:"酪梨",
        eng:"sidefood4",
        price:20,
        cal:"62cal",
        imgURL:"../img/restaurant/egg2.png"
      },
    ],

    humanFoodSelect:"美式",
    petFoodSelect:"沙拉",
    humanFoodType:["美式","義式"],
    petFoodType:["沙拉","主食","鮮食"],
    humanFoodMenu:[
      {
        type:"美式",
        name:"安格斯牛肉漢堡",
        price:100,
        cal:"120cal",
      },
      {
        type:"美式",
        name:"費城牛肉三明治",
        price:120,
        cal:"300cal",
      },
      {
        type:"美式",
        name:"炸物拼盤",
        price:500,
        cal:"500cal",
      },
      {
        type:"美式",
        name:"凱薩沙拉",
        price:80,
        cal:"90cal",
      },
      {
        type:"美式",
        name:"碳烤豬肋排",
        price:500,
        cal:"260cal",
      },
      {
        type:"義式",
        name:"番茄義大利麵",
        price:200,
        cal:"220cal",
      },
      {
        type:"義式",
        name:"羅勒青醬義大利麵",
        price:320,
        cal:"200cal",
      },
      {
        type:"義式",
        name:"蛤蠣奶油義大利麵",
        price:200,
        cal:"500cal",
      },
      {
        type:"義式",
        name:"雙層美式臘腸披薩",
        price:300,
        cal:"400cal",
      },
      {
        type:"義式",
        name:"彩蔬鮮菇披薩",
        price:390,
        cal:"290cal",
      },
    ],
    petFoodMenu:[
      {
        type:"沙拉",
        name:"雞肉沙拉",
        price:200,
        cal:"200cal",
      },
      {
        type:"沙拉",
        name:"牛肉沙拉",
        price:299,
        cal:"230cal",
      },
      {
        type:"沙拉",
        name:"嫩煎鮭魚沙拉",
        price:270,
        cal:"220cal",
      },
      {
        type:"鮮食",
        name:"低敏結實配方",
        price:370,
        cal:"250cal",
      },
      {
        type:"鮮食",
        name:"關節保養配方",
        price:570,
        cal:"230cal",
      },
      {
        type:"鮮食",
        name:"毛髮亮麗配方",
        price:170,
        cal:"320cal",
      },
      {
        type:"鮮食",
        name:"元氣滿滿­­配方",
        price:470,
        cal:"280cal",
      },
    ]
  },
  methods: {
    choosePetCustomFood(name){
      if(this.petCustomFoodChosen.indexOf(name) ==-1){
        this.petCustomFoodChosen.push(name);
      }
    }
  },
  computed: {
    humanFoodSelected(){
      return this.humanFoodMenu.filter((item)=>{
        return item.type === this.humanFoodSelect
      })
    },
    petFoodSelected(){
      return this.petFoodMenu.filter((item)=>{
        return item.type === this.petFoodSelect
      })
    }
  },
})